[build]
  base = "/"
  publish = "dist"
  functions = "netlify/functions"
  command = "npm run build"

[deploy]
  logs = "public"  # Choose between "public" or "private"
  status = "active"  # Choose between "active" or "stopped"