[build]
  base = "frontend"  # Set the base directory to your frontend
  command = "npm run build"
  publish = "dist"  # Adjust this path according to your frontend build output
  functions = "backend/functions"
  node_version = "16"

[deploy]
  logs = "public"  # Choose between "public" or "private"
  status = "active"  # Choose between "active" or "stopped"

[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Headers = "*"
    Access-Control-Allow-Methods = "GET, POST, PUT, DELETE, OPTIONS"
